// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrenCR.Data;

namespace TrenCR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrenCR.Model.Boletos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cantidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Horario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Boletos");
                });

            modelBuilder.Entity("TrenCR.Model.Cartago_SanJose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cfia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstacionAtlantico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstacionCartago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LosAngeles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TresRios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UACA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UCR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulatina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CS");
                });

            modelBuilder.Entity("TrenCR.Model.SanJose_Cartago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cfia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstacionAtlantico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstacionCartago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LosAngeles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TresRios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UACA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UCR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulatina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SC");
                });
#pragma warning restore 612, 618
        }
    }
}
